### ISSUE TITLE
Game closes after injection

### ISSUE THREAD

**Issue by M4gnuson** [winstxnhdw/lc-hax#7]
I'm using the same injector as yours. Error:
Injection failed: mono_object_get_class() returned NULL.
Namespace: Hax
Class: Loader
Method: Load

**Comment by winstxnhdw** [comment]
Make sure you are on the latest commit. I just fixed that more than an hour ago.

**Comment by M4gnuson** [comment]
> Make sure you are on the latest commit. I just fixed that more than an hour ago.

Yes, I checked. The error is still there

Time has passed 00:00:00.88
Injection failed: SharpMonoInjector.InjectorException: mono_object_get_class() returned NULL
   at SharpMonoInjector.Injector.ThrowIfNull(IntPtr ptr, String methodName)
   at SharpMonoInjector.Injector.GetClassName(IntPtr monoObject)
   at SharpMonoInjector.Injector.RuntimeInvoke(IntPtr method)
   at SharpMonoInjector.Injector.Inject(Byte[] rawAssembly, String namespace, String className, String methodName)
   at Program.<<Main>$>g__Inject|0_0(String targetProcess, FileInfo assembly, String loaderNamespace, String loaderClass, String loaderMethod)

**Comment by winstxnhdw** [comment]
Are you using my injector or are you using some other version of SharpMonoInjector?

**Comment by M4gnuson** [comment]
> Are you using my injector or are you using some other version of SharpMonoInjector?

Is yours

**Comment by winstxnhdw** [comment]
Strange. I have no clue. My friends and I are running it fine right now. Can you go to your `steamapps\common\Lethal Company` folder and send the `lc-hax.log` if any?

**Comment by M4gnuson** [comment]
> Strange. I have no clue. My friends and I are running it fine right now. Can you go to your `steamapps\common\Lethal Company` folder and send the `lc-hax.log` if any?

There is no such(lc-hax.log)

**Comment by M4gnuson** [comment]
I reinstalled the game. He got injected. Are there any keys to open the console?

**Comment by winstxnhdw** [comment]
We use the chat for console.

**Comment by FatFishFF** [comment]
greeting,i met the same question
i checked my game file and discovered "lc-hax.log" but still crash after inj
![88d4cfe84f2e5c6b608262646f18c190](https://github.com/winstxnhdw/lc-hax/assets/160096918/93934b27-2c74-475d-bbee-f0dbac7cc24e)

**Comment by winstxnhdw** [comment]
Send the log.
