### ISSUE TITLE
[Bug]: Unable to interact in `Phantom` and blocking credits crashes the game

### ISSUE THREAD

**Issue by yujispin990** [winstxnhdw/lc-hax#87]
### What happened?

Ok so, on phantom, i cannot grab anything, infinite grab does not allow interaction with some stuff like the ship lever or the terminal, /block commands are not found.

### Current Commit Hash

3a1a64d

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by yujispin990** [comment]
those are the things i found so far, i am actually testing it right now.

**Comment by winstxnhdw** [comment]
My bad, I've added the `block` command.

**Comment by yujispin990** [comment]
> My bad, I've added the `block` command.

Woah that was fast thank you! may i ask what about the grab not letting me interact with things.

**Comment by winstxnhdw** [comment]
Is it only in `Phantom` or outside as well?

**Comment by yujispin990** [comment]
on phantom i could not grab anything and when im not in phantom i can grab stuff like the clipboard from the ship really far away but i cant interact with the terminal or the ship's lever. Let me update and test it again.

**Comment by winstxnhdw** [comment]
That's really strange :/ I'll have to take a look at it tomorrow. I don't have access to the game right now. For now, you can use `/start` or `/end` to use the lever and `/fixcamera` to use the Terminal.

**Comment by yujispin990** [comment]
Alrighty, Thank you for the fast response @winstxnhdw <3

**Comment by winstxnhdw** [comment]
No need to close it unless we get it fixed.

**Comment by yujispin990** [comment]
> No need to close it unless we get it fixed.

Ah i see, Thank you so much!

**Comment by winstxnhdw** [comment]
Nevermind, I think I found the issue. I've pushed a fix. Please test it again.

**Comment by yujispin990** [comment]
> Nevermind, I think I found the issue. I've pushed a fix. Please pull latest and test it again.

Oh no i forgot to tell you as well, i still get "hands full" even with the one handed patch. I will update now to test the grab first.

**Comment by winstxnhdw** [comment]
Okay, I have pushed a fix for that as well.

**Comment by yujispin990** [comment]
Ok nice! the grab is fixed! but i still cannot grab anything when in phantom.

**Comment by yujispin990** [comment]
> Okay, I have pushed a fix for that as well.

Alrighty ill test it now.

**Comment by winstxnhdw** [comment]
> i still cannot grab anything when in phantom.

Could you test if you can interact with the ship lever while in `Phantom`?

**Comment by yujispin990** [comment]
> > i still cannot grab anything when in phantom.
> 
> Could you test if you can interact with the ship lever while in `Phantom`?

Ok, ill do it right now.

**Comment by joep26020** [comment]
> Ok nice! the grab is fixed! but i still cannot grab anything when in phantom.

The grab icon is stuck on my screen.

**Comment by winstxnhdw** [comment]
@yujispin990 could you help me verify if what @joep26020 is saying is true? He's usually not on the latest version.

**Comment by joep26020** [comment]
> @yujispin990 could you help me verify if what @joep26020 is saying is true? He's usually not on the latest version.

No I am. Whenever I pick up an item though it goes away.

**Comment by winstxnhdw** [comment]
Can you look up at the sky and tell me if you are getting the same problem?

**Comment by yujispin990** [comment]
> @yujispin990 could you help me verify if what @joep26020 is saying is true? He's usually not on the latest version.

Nope, no problem with that at all, also i've tested one handed patch and it works perfectly! as for the Phantom grab, i cannot interact with the ship lever or anything else.

**Comment by winstxnhdw** [comment]
Okay, thank you @yujispin990!

**Comment by yujispin990** [comment]
i have no floating icon on mine.

**Comment by yujispin990** [comment]
> Okay, thank you @yujispin990!

No, Thank you for staying up this late to work on this, i do apologize for being a nuisance.

**Comment by joep26020** [comment]
Ok just updated it and it's gone now. But the weird thing is I updated it an hour ago. I guess that made a difference. I'll shut up now.

**Comment by joep26020** [comment]
Start ship works lol

**Comment by winstxnhdw** [comment]
Has been for a really long time now.

**Comment by yujispin990** [comment]
I found a funny "bug?" though, if you block credits and try to add money with /money, the game instantly crash xd, there is no need to fix this. Just thought it might tell you.

**Comment by winstxnhdw** [comment]
That's useful information. I'll push a fix for it.

**Comment by winstxnhdw** [comment]
Nevermind, thinking about it. It shouldn't even crash. It might be a sign of a bug. Can you try selling items with it on. I am afraid it might also crash your game. Or whenever someone else uses `/money`.

**Comment by yujispin990** [comment]
> That's useful information. I'll push a fix for it.

Alrighty then! Again i can't thank you enough for staying up this late to fix all these things.

**Comment by yujispin990** [comment]
> Nevermind, thinking about it. It shouldn't even crash. It might be a sign of a bug. Can you try selling items with it on. I am afraid it might also crash your game. Or whenever someone else uses `/money`.

Ok ill do it right now.

**Comment by winstxnhdw** [comment]
Wait, before you do that can you pull latest. I have pushed a preliminary fix. I think it was calling itself recursively and creating a stack overflow. Try turning it on and doing `/money 1` again.

**Comment by yujispin990** [comment]
Oh i tested by selling a shotgun and it didn't block the credit, its still gets added in. I will update to the latest right now.

**Comment by yujispin990** [comment]
> Wait, before you do that can you pull latest. I have pushed a preliminary fix. I think it was calling itself recursively and creating a stack overflow. Try turning it on and doing `/money 1` again.

I've updated and tested with /money 1, it still gets added in and in addition to that when i used /money 100 it crashed instantly.

**Comment by winstxnhdw** [comment]
I rebased earlier, so you might have to pull again for the true latest.

**Comment by winstxnhdw** [comment]
Okay, I am going to stop here. I am making a lot of stupid mistakes right now. I'll continue tomorrow.

**Comment by yujispin990** [comment]
> I rebased earlier, so you might have to pull again for the true latest.

Ill try it right now.

**Comment by yujispin990** [comment]
> Okay, I am going to stop here. I am making a lot of stupid mistakes right now. I'll continue tomorrow.

Ah, no worries my dude, take your time and thank you again for spending time on this.

**Comment by yujispin990** [comment]
Ok just tested the latest one, i used /money 1 after block credits, it instantly crashes, but its ok, please have some rest, continue anytime you would like, honestly if it this much hassle it might be better to just remove it completely. I'm sorry for even suggesting this.

**Comment by winstxnhdw** [comment]
I'll temporarily disable so it doesn't crash other people's game.

**Comment by winstxnhdw** [comment]
`/block credits` is now fixed. It will even inform you if someone has tried to modify the credits.

**Comment by winstxnhdw** [comment]
You can now grab in `Phantom`!
